# Generated by Django 4.1.3 on 2022-12-14 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                (
                    "part_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Артикул"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "В наличии"),
                            (1, "Под заказ"),
                            (2, "Ожидается поступление"),
                            (3, "Нет в наличии"),
                            (4, "Не производится"),
                        ],
                        verbose_name="Статус",
                    ),
                ),
                (
                    "orig_image",
                    models.ImageField(
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png"]
                            )
                        ],
                        verbose_name="Изображение (jpg/png)",
                    ),
                ),
                ("webp_image", models.ImageField(upload_to="")),
            ],
        ),
    ]
